// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEydic-37me6ZGp5aIRLR1FA4qBovzTQs',
    appId: '1:1071981733640:web:8f7d1a8f611d09526aaebd',
    messagingSenderId: '1071981733640',
    projectId: 'ancientquotesfirebase',
    authDomain: 'ancientquotesfirebase.firebaseapp.com',
    storageBucket: 'ancientquotesfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM3UcO1AY_BUyIVEFdPcborAQdM9rf0tc',
    appId: '1:1071981733640:android:8319eca4339668cd6aaebd',
    messagingSenderId: '1071981733640',
    projectId: 'ancientquotesfirebase',
    storageBucket: 'ancientquotesfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDWONXeIu5t9KujF7Kj0gdDsPq9SJeRA',
    appId: '1:1071981733640:ios:537819b143d611f96aaebd',
    messagingSenderId: '1071981733640',
    projectId: 'ancientquotesfirebase',
    storageBucket: 'ancientquotesfirebase.firebasestorage.app',
    iosBundleId: 'com.example.ancientQuotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMDWONXeIu5t9KujF7Kj0gdDsPq9SJeRA',
    appId: '1:1071981733640:ios:537819b143d611f96aaebd',
    messagingSenderId: '1071981733640',
    projectId: 'ancientquotesfirebase',
    storageBucket: 'ancientquotesfirebase.firebasestorage.app',
    iosBundleId: 'com.example.ancientQuotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEydic-37me6ZGp5aIRLR1FA4qBovzTQs',
    appId: '1:1071981733640:web:fa29c718552900f26aaebd',
    messagingSenderId: '1071981733640',
    projectId: 'ancientquotesfirebase',
    authDomain: 'ancientquotesfirebase.firebaseapp.com',
    storageBucket: 'ancientquotesfirebase.firebasestorage.app',
  );
}
